### ISSUE TITLE
project.json.lock is getting updated without my consent

### ISSUE THREAD

**Issue by nathanielcook** [mrward/monodevelop-dnx-addin#10]
First of all, very excited about this add-in. I was able to get debugging working with Xamarin Studio 5.10.1 by installing Mono 4.3.2.221 manually from [here](http://download.mono-project.com/archive/nightly/macos-10-universal/).

The problem is that, even if I turn off `Preferences -> NuGet -> Package Restore -> Automatically restore packages when opening a solution` and `Preferences -> NuGet -> Package Update -> Check for package updates when opening a solution` somehow my project.json.lock file is still getting updated as I work with the ASP.NET 5 project in Xamarin Studio. I'm not sure when exactly it is happening. I think it is happening on file save, depending on what file I have open.

This is a problem because at the moment I need to work with a specific version of RC2. Yet it keeps getting upgraded to later bleeding edge versions of RC2 that I haven't been able to get working on my system yet. I could go through and set the exact version of every dependency in project.json, but it seems like that shouldn't be necessary. The update of dependencies should happen only when I ask it to, no? For now I am stuck to using another editor until this is fixed, or a solid workaround can be found.

**Comment by mrward** [comment]
This will be because there is no way to turn off `dnu restore` currently which will generate a new project.json.lock file.

The NuGet options/preferences do not affect the DNX addin. Ideally I do not want to tie the DNX addin to the NuGet addin since that has caused me problems in the past when NuGet.Core was upgraded, which causes type load exceptions on the Mac. So I plan to add a separate preferences page to enable/disable the package restore for DNX projects.

**Comment by nathanielcook** [comment]
A separate preferences page sounds good to me.

**Comment by mrward** [comment]
I have a new build of the addin available on [github](https://github.com/mrward/temp-addin-upload/blob/master/Dnx/MonoDevelop.Dnx_0.1.1.mpack). You can download that and use the Add-in Manager to install the .mpack file.

This new addin adds a check box to the DNX - General section in preferences which you can use to disable/enable DNX restore.

<img width="705" alt="dnxrestore" src="https://cloud.githubusercontent.com/assets/372361/12216189/0e89e148-b6d2-11e5-9b3d-d3f0df6185cb.png">
