### ISSUE TITLE
Hide backup files?

### ISSUE THREAD

**Issue by fogzot** [mrward/monodevelop-dnx-addin#13]
A DNX project by default shows all the files in the project tree. With automatic backup files on things become a mess quite rapidly. I was thinking about hiding _at least_ the backup files generated by MonoDevelop, i.e., `*~` ones.

**Comment by mrward** [comment]
Not adding the MonoDevelop backup files sounds good to me.

**Comment by mrward** [comment]
This has now been fixed in master.
