### ISSUE TITLE
v0.1.1 - Location of Pads in Xamarin Studio (5.10.1) get reset

### ISSUE THREAD

**Issue by nathanielcook** [mrward/monodevelop-dnx-addin#16]
Using v0.1.1 (with the "automatically restore dependencies" checkbox) the location of the Xamarin Studio pads (such as the solution pad, errors pad, unit tests pad, etc) are reset to their default configurations upon opening the DNX project (or upon opening Xamarin Studio? I'm not sure at what point it happens because the pads aren't visible until I open a project). I didn't experience this behavior with v0.1.

**Comment by nathanielcook** [comment]
Update on this: it seems to be that all preferences are reset, not just the location of the pads. So this is actually more than just an annoyance.

**Comment by nathanielcook** [comment]
Sorry, one more quick update: it looks like some preferences were preserved. What I know for sure get reset are the location of the pads as well as the setting "Disable Version Control globally".

**Comment by mrward** [comment]
Unable to repro this with Mono 4.2 or Mono 4.3.221. I am also not sure how version 0.1.1 affects Xamarin Studio whilst 0.1 does not. The changes made for 0.1.1 only include the change to support the new DNX restore preference. Layout information is stored separately to the other preferences, although the version control preference will be stored with the DNX restore preference.

Is there anything in the IDE log? (Help - Open Log Directory).

**Comment by mrward** [comment]
I suspect the "Too many open files" caused the problem with saving any preferences. In one of the log files I can see the too many open files error and then at the end an "Error while saving layout.".

**Comment by nathanielcook** [comment]
That makes sense. If you like you can close this issue and we'll just track the other one until we get that one figured out. Then we can re-open this one if there are any additional issues.
