### ISSUE TITLE
Intellisense in Xamarin Studio 6 doesn't work... 

### ISSUE THREAD

**Issue by mleader1** [mrward/monodevelop-dnx-addin#18]
As topic says...

I used Xamarin Studio 5.10 it worked; and then I liked the Xamarin Studio 6 visual style so upgraded and compiled DNX addin from this repo - installed without much issue, but the Intellisense stopped working on all files (including c# files, javascript files all files).

Did I miss anything during the compilation or is this a bug?

Thanks.

**Comment by mleader1** [comment]
NOTE: if I create a normal asp.net MVC5 project or any other project types, everything works again. so it might be DNX project specific problem.  Any suggestions please...

**Comment by mrward** [comment]
Which branch did you use? The roslyn branch targets Xamarin Studio 6.0 and it should work with latest monodevelop/master. Not tried it with Xamarin Studio 6.0 preview 4.

Otherwise I would suggest you look in the IDE log (Help - Open Log Directory).

**Comment by mleader1** [comment]
Yes I'm using the Preview 4...

I'll give it a try Preview 3 if I can find the download link otherwise will check out the logs  thx

**Comment by mleader1** [comment]
hi @mrward 

Yes confirmed - there's no particular error in the IDE log, everything works except intellisense.  I have now reverted back to the stable version + DNX which works perfectly... If it is something you can fix that'd be great otherwise I think I'd better wait till there's an official release of the pretty XS 6  :)

cheers.

**Comment by mrward** [comment]
It looks like this [MonoDevelop commit](https://github.com/mono/monodevelop/commit/a49d6220af5f369dcc243dde21c018b20755a846) has broken the DNX addin. With the current MonoDevelop the type system excludes all projects that do not have a TypeGuid that matches one of the following:
- {FAE04EC0-301F-11D3-BF4B-00C04F79EFBC} = C#
- {F184B08F-C81C-45F6-A57F-5ABD9991F28F} = VB.NET

DNX projects have a different TypeGuid so the projects are not used by the type system so there is no code completion.

It looks like I cannot fix this from the DNX addin. If I change the type guid to C# the wrong one will be saved into the solution. I suspect that MonoDevelop 6.0 will need to be changed so the type guids are not hard coded.

**Comment by mleader1** [comment]
looks like we'll have to wait..  it's nice to see all the C# 6.0 is coming into XS but without DNX support I'll have to use Visual Studio VM for now.

Thanks @mrward

**Comment by nathanielcook** [comment]
@mrward did you open a bugzilla so the MonoDevelop team will be aware of the issue?

**Comment by mrward** [comment]
@nathanielcook I have not opened a bug report since both myself and David Karlaš are aware of the problem. We also both work on MonoDevelop :smile:

**Comment by nathanielcook** [comment]
haha, great :-)

**Comment by mrward** [comment]
Opened [pull request](https://github.com/mono/monodevelop/pull/1245) on the MonoDevelop repository.

**Comment by mrward** [comment]
Pull request has been merged to monodevelop/master.
