### ISSUE TITLE
When adding a project name with namespaces (2 or more dots) only first 2 sections are created

### ISSUE THREAD

**Issue by mleader1** [mrward/monodevelop-dnx-addin#21]
How to reproduce:

Step 1) Create a solution, right click on "src" to create a new project "ABC.BCD.CDE";  
- Issue 1: the project is created successfully in file system as "ABC.BCD.CDE", however the project name and default namespace are created as "ABC.BCD" which is wrong
  Step 2) Create one more project named "ABC.BCD.DEF";
- Issue 1:  same as above, project in file system was created correctly, but project name and default namespace are all "ABC.BCD"

So now I have 2 projects with the same names exists in my solution

Now Issue 2:

If I right click on the solution node for creating a new project, the project gets created at parent folder of "src" folder, which I thin is wrong?

Cheers.   (I like this addin, thx!)

**Comment by mrward** [comment]
Issue 1 is now fixed.

Issue 2 - Right clicking on the src or solution and creating a new DNX project will always add the project inside the src directory. If you right click the solution and add a non-DNX project, say an NUnit Library project, then that project will be created directly inside the solution directory and not the src directory. The DNX addin has no control over other non-DNX project templates being created outside the src directory. It only supports DNX projects being created inside the src directory. Can you provide a way to reproduce the problem you are seeing?

**Comment by mleader1** [comment]
hi @mrward 

Yes sorry I've now double checked it seems working fine (issue 2 - It did happen but I could reproduce it myself...)

However I did find this UI issue:

Step 2.  As seen in the screenshot, the "src" folder is not seen in either Location input textbox, nor in the right panel treeview.  I guess that probably was the reason I got confused? But it's a minor bug anyway, the file system seems working properly!

![image](https://cloud.githubusercontent.com/assets/5477158/12870132/4b15bc78-cd2e-11e5-9ad6-d3e1c222746a.png)

**Comment by mrward** [comment]
Unfortunately an addin has no control over what is displayed in the New Project dialog's preview. The preview makes some assumptions about the final directory layout of the project. Ideally an addin would have some way of providing information for the preview window so it could properly reflect the directory structure, but that is not supported by the New Project dialog currently.
