### ISSUE TITLE
Provide instructions to build the addin package

### ISSUE THREAD

**Issue by ccidral** [mrward/monodevelop-dnx-addin#3]
I tried to build the addin package but the resulting `.mpack` file cannot be installed by MonoDevelop. These are the steps I took (not sure that they are correct):

```
cd src
nuget restore MonoDevelop.Dnx.sln
cd ..
mdtool build src\MonoDevelop.Dnx.sln
mdtool setup pack addin-project.xml
```

Attempts to install the `.mpack` file in MonoDevelop have no effect, not even error messages, it simply doesn't install the addin. I noticed that the size of the `.mpack` file doesn't look right (400 bytes) which makes me think it wasn't built correctly using the procedure above.

By the way thanks for writing this addin, it's going to be very useful.

**Comment by mrward** [comment]
The last step should be:

```
mdtool setup pack bin\merged\MonoDevelop.Dnx.dll
```

**Comment by geoffrey-vl** [comment]
Notice that you also might want to update MonoDevelop to the version 5.9.6, otherwise the addin cannot be installed.

**Comment by ccidral** [comment]
Thanks a lot, it worked.
