### ISSUE TITLE
Application Output pad not showing Console.WriteLine statements

### ISSUE THREAD

**Issue by vimception** [mrward/monodevelop-dnx-addin#33]
I have noticed none of my Console.WriteLine statements end up in the Application Output pad of Xamarin Studio when running a .NET Core app. I don't know if it is the responsibility of the dnx addin, or if this is just a known issue/limitation at this point. I've been watching the .NET Core Output pad as well, but this only shows errors from the project.json file as far as I can tell.

I'm running XS Version 6.0 (build 5174) on Mac 10.11.5 with the DNX and VSCodeDebugger add-ins installed.

**Comment by mrward** [comment]
The DNX addin should work the same as running a normal .NET application. So by default Console.WriteLine output is displayed in the external console that is opened. If you go into project options and in Run - General uncheck Run on external console then Console.WriteLine output is then shown in the Application Output window. This seems to be the case for me.

The .NET Core output window will not show output from your .NET Core application.

The .NET Core output pad is for seeing what the .NET Core design time host is doing and why it may be failing. It shows messages between Xamarin Studio and the .NET Core design time host and errors.
