### ISSUE TITLE
Debug doesn't seem to work on Linux + MonoDevelop 6.2

### ISSUE THREAD

**Issue by salaros** [mrward/monodevelop-dnx-addin#36]
Somehow only the projects created using project templates provided by the addin work correctly.
After altering project.json (for example adding new dependencies, switching to netcoreapp 1.0.1 etc) or adding ASP.NET Core MVC elements even those sample projects will build and run correctly, but will fail to debug (somehow breakpoints seem to be ignored)

P.S. I can send you some samples if you won't be able to reproduce this issue on your PC/Mac

**Comment by mrward** [comment]
Currently the [debugger](https://github.com/DavidKarlas/VSCodeDebugger) that works with the DNX addin only supports the Mac. It basically ships the Mac specific files with the addin so it does not work on any other operating system.

Looks like you have [opened an issue in the debugger GitHub repository](https://github.com/DavidKarlas/VSCodeDebugger/issues/2) for this already. So I will close this issue.
