### ISSUE TITLE
Question: Does the mono soft debugger support .net core?

### ISSUE THREAD

**Issue by danwalmsley** [mrward/monodevelop-dnx-addin#37]
Hi, 
    I see you have used the Mono.SoftDebugger to debug dnx assemblies. I am interested in integrating debug support in another open source IDE (GitHub.com/vitalelement/avalonstudio)

I tried to use the soft debugger command line to debug a hello world application compiled with dot net core...

![image](https://cloud.githubusercontent.com/assets/4672627/20649268/5443bddc-b4b3-11e6-9171-4be815e28c48.png)

Should this work? Did you have to do anything special to make it work in Monodevelop?

**Comment by mrward** [comment]
The MonoDevelop DNX addin uses the debugger that VSCode uses. This is made available from a [custom debugger addin](https://github.com/DavidKarlas/VSCodeDebugger) for MonoDevelop. The soft debugger on the command line would have no knowledge of this VSCode debugger so I would not expect that to work.
