### ISSUE TITLE
Can we have an updated version for Core 1.1?

### ISSUE THREAD

**Issue by jradxl** [mrward/monodevelop-dnx-addin#38]
I'm using MonoDevelop 6.2.0.1812, with Mono 4.8.0.495
I've been able to build the Addin (v 0.6) with difficulty (for example ILRepack is not in package.config)
And it installs OK.
But running it is terribly slow, and a simple console app hangs on load at "Loading workspace documents".

Is this an ongoing project?
Thx

**Comment by mrward** [comment]
ILRepack is in the src/.nuget/packages.config file. It should restore if you run a restore for the entire solution from the command line.

project.json + .xproj have been made obsolete and are replaced with .csproj files and PackageReferences. Support for this new .NET Core project file format is currently available in Visual Studio for Mac. Since project.json + .xproj have been made obsolete I am not actively working on this addin.

**Comment by jradxl** [comment]
Pity!
Thanks for quick response.
Someone is working on similar for Eclipse! https://github.com/mickaelistria/aCute
Sorry, my nuget,exe wasn't working. MonoDevelop only restored project dependencies.
Thx.

**Comment by mrward** [comment]
So I had a quick look at this. The .NET Core SDK 1.0.1 (.NET Core runtime 1.1 and 1.0) does not support project.json apart from migrating it to the new format. It does not look like the projectmodel-server command line argument is supported any more. This seems to have been removed around [preview 3](https://github.com/dotnet/cli/commit/6fcbefa4f7a0016a68d3cda52779298a5cd20837). This was used by the DNX addin to get all the information about the project, such as references.

The latest C# plugin, which uses Omnisharp, for VSCode seems to upgrade project.json files to .csproj files.

So I think the only way the DNX addin would work is if you use an old version of .NET Core which still has the projectmodel-server command.

**Comment by craigfowler** [comment]
> Since project.json + .xproj have been made obsolete I am not actively working on this addin.

> So I think the only way the DNX addin would work is if you use an old version of .NET Core which still has the projectmodel-server command.

Those things said - would it be reasonable to alter the README for this repo.  Indicating that it is not currently under development and won't support the current .NET Core?  I only discovered that it wouldn't work after I'd downloaded the add-in and spent a while trying to figure out why it wasn't working (including visiting the github issues).

**Comment by mrward** [comment]
@craigfowler - Sure. I have updated the readme.
