### ISSUE TITLE
The following steps from https://github.com/mrward/monodevelop-dnx-addin/tree/roslyn have errors in them

### ISSUE THREAD

**Issue by frankchang91** [mrward/monodevelop-dnx-addin#8]
The following steps from https://github.com/mrward/monodevelop-dnx-addin/tree/roslyn have errors in them

Building from source From the src directory run NuGet restore. git clone https://github.com/mhutch/MonoDevelop.AddinMaker
cd MonoDevelop.AddinMaker
nuget restore MonoDevelop.AddinMaker.sln
make install /p:MDBinDir=../monodevelop/main/build/bin /p:MDProfileVersion=6.0

```
The above line results in No rule to make target install'.Stop. * git clone git@github.com:mrward/monodevelop-dnx-addin.git cd monodevelop-dnx-addins git checkout roslyn cd src nuget restore MonoDevelop.Dnx.sln xbuild MonoDevelop.Dnx.sln /p:MDProfileVersion=6.0 /p:MDBinDir=../../../monodevelop/main/build/bin The above line results in the C# compiler error : /opt/mono-2015.12.10+23.35.44/lib/mono/4.5/Microsoft.CSharp.targets (CoreCompile target) -> MonoDevelop.Dnx/DnxProjectService.cs(139,20): error CS0117:MonoDevelop.Ide.DispatchService' does not contain a definition for `GuiDispatch' Any help is appreciated.
```

**Comment by mrward** [comment]
The compile error is from the DNX addin. There have been some API changes in MonoDevelop recently around the DispatchService which have broken compilation. So the DNX addin needs to be updated to support the latest code from MonoDevelop's master branch.

**Comment by mrward** [comment]
The DispatchService compilation error has [now been fixed](https://github.com/mrward/monodevelop-dnx-addin/commit/c31e1bc291f0307f24ee039ca5f56b596cab68fe) with the latest code from the roslyn branch.
